/**
 * Hollow STL Utility
 * Hollows solid STL files using OpenSCAD boolean subtraction.
 * Creates a shell by subtracting a scaled-down copy from the original,
 * preserving the bottom thickness via Z-axis translate.
 */

const fs = require('fs');
const path = require('path');
const os = require('os');
const crypto = require('crypto');
const { spawn } = require('child_process');

const OPENSCAD_BIN = process.env.OPENSCAD_PATH || 'openscad';
const OPENSCAD_TIMEOUT_MS = 600000; // 10 minutes (large vase STLs with CGAL can be very slow)

/**
 * Parse an STL file and extract bounding box dimensions.
 * Handles both binary and ASCII formats.
 * @param {string} filePath - Absolute path to STL file
 * @returns {{ x: number, y: number, z: number }}
 */
function getStlDimensions(filePath) {
  const buffer = fs.readFileSync(filePath);
  const bbox = { minX: Infinity, maxX: -Infinity, minY: Infinity, maxY: -Infinity, minZ: Infinity, maxZ: -Infinity };

  // Detect ASCII vs binary
  const header = buffer.slice(0, 80).toString('utf8').trim();
  const isAscii = header.startsWith('solid') &&
    buffer.slice(0, Math.min(buffer.length, 1000)).toString('utf8').includes('facet normal');

  if (isAscii) {
    const text = buffer.toString('utf8');
    const re = /vertex\s+([-\d.eE+]+)\s+([-\d.eE+]+)\s+([-\d.eE+]+)/g;
    let m;
    while ((m = re.exec(text)) !== null) {
      const x = parseFloat(m[1]), y = parseFloat(m[2]), z = parseFloat(m[3]);
      if (isFinite(x) && isFinite(y) && isFinite(z)) {
        bbox.minX = Math.min(bbox.minX, x); bbox.maxX = Math.max(bbox.maxX, x);
        bbox.minY = Math.min(bbox.minY, y); bbox.maxY = Math.max(bbox.maxY, y);
        bbox.minZ = Math.min(bbox.minZ, z); bbox.maxZ = Math.max(bbox.maxZ, z);
      }
    }
  } else {
    if (buffer.length < 84) throw new Error('STL file too small to parse');
    const triCount = buffer.readUInt32LE(80);
    const actual = Math.min(triCount, Math.floor((buffer.length - 84) / 50));
    for (let i = 0; i < actual; i++) {
      const off = 84 + i * 50;
      for (let v = 0; v < 3; v++) {
        const vo = off + 12 + v * 12;
        if (vo + 12 > buffer.length) break;
        const x = buffer.readFloatLE(vo), y = buffer.readFloatLE(vo + 4), z = buffer.readFloatLE(vo + 8);
        if (isFinite(x) && isFinite(y) && isFinite(z)) {
          bbox.minX = Math.min(bbox.minX, x); bbox.maxX = Math.max(bbox.maxX, x);
          bbox.minY = Math.min(bbox.minY, y); bbox.maxY = Math.max(bbox.maxY, y);
          bbox.minZ = Math.min(bbox.minZ, z); bbox.maxZ = Math.max(bbox.maxZ, z);
        }
      }
    }
  }

  return {
    x: Math.round((bbox.maxX - bbox.minX) * 100) / 100,
    y: Math.round((bbox.maxY - bbox.minY) * 100) / 100,
    z: Math.round((bbox.maxZ - bbox.minZ) * 100) / 100
  };
}

/**
 * Generate the .scad file content for hollowing an STL via boolean subtraction.
 *
 * @param {string} stlPath     - Absolute path to the input STL (forward slashes)
 * @param {number} scaleX      - X scale factor for inner cavity
 * @param {number} scaleY      - Y scale factor for inner cavity
 * @param {number} scaleZ      - Z scale factor for inner cavity
 * @param {number} wallThickness - Bottom wall thickness in mm (translate Z offset)
 */
function generateHollowScad(stlPath, scaleX, scaleY, scaleZ, wallThickness) {
  const safePath = stlPath.replace(/\\/g, '/');
  return `// Auto-generated by Hollow STL Utility
difference() {
  import("${safePath}");
  translate([0, 0, ${wallThickness}])
    scale([${scaleX}, ${scaleY}, ${scaleZ}])
      import("${safePath}");
}
`;
}

/**
 * Run OpenSCAD headlessly to produce an STL from a .scad file.
 * @param {string} scadPath   - Path to the .scad script
 * @param {string} outputPath - Path for the output STL
 * @returns {Promise<{stdout: string, stderr: string}>}
 */
function runOpenScad(scadPath, outputPath) {
  return new Promise((resolve, reject) => {
    const args = ['-o', outputPath, scadPath];
    const proc = spawn(OPENSCAD_BIN, args, {
      stdio: ['ignore', 'pipe', 'pipe']
    });

    let stdout = '';
    let stderr = '';
    let killed = false;
    proc.stdout.on('data', (d) => { stdout += d.toString(); });
    proc.stderr.on('data', (d) => { stderr += d.toString(); });

    // Manual timeout — more reliable than spawn's timeout option
    const timer = setTimeout(() => {
      killed = true;
      proc.kill('SIGKILL');
    }, OPENSCAD_TIMEOUT_MS);

    proc.on('error', (err) => {
      clearTimeout(timer);
      if (err.code === 'ENOENT') {
        reject(new Error(`OpenSCAD not found at "${OPENSCAD_BIN}". Install with: sudo apt install openscad`));
      } else {
        reject(err);
      }
    });

    proc.on('close', (code, signal) => {
      clearTimeout(timer);
      if (killed) {
        reject(new Error(`OpenSCAD timed out after ${OPENSCAD_TIMEOUT_MS / 1000}s — model may be too complex for CGAL. stderr: ${(stderr || '').slice(0, 300)}`));
      } else if (code === 0) {
        resolve({ stdout, stderr });
      } else {
        // OpenSCAD may exit with code 1 but still produce valid output (CGAL warnings)
        if (fs.existsSync(outputPath) && fs.statSync(outputPath).size > 0) {
          console.warn(`[Hollow] OpenSCAD exited with code ${code} but output exists — treating as success`);
          resolve({ stdout, stderr });
        } else {
          reject(new Error(`OpenSCAD exited with code ${code}${signal ? ' (signal: ' + signal + ')' : ''}: ${stderr || 'unknown error'}`));
        }
      }
    });
  });
}

/**
 * Compute scale factors for hollowing based on bounding box dimensions and wall thickness.
 *
 * @param {number} dimX - Model width in mm
 * @param {number} dimY - Model depth in mm
 * @param {number} dimZ - Model height in mm
 * @param {number} wallThickness - Desired wall thickness in mm
 * @returns {{ scaleX: number, scaleY: number, scaleZ: number }}
 */
function computeScaleFactors(dimX, dimY, dimZ, wallThickness) {
  if (dimX < wallThickness * 3 || dimY < wallThickness * 3 || dimZ < wallThickness * 3) {
    throw new Error(
      `Model too small to hollow: ${dimX.toFixed(1)} x ${dimY.toFixed(1)} x ${dimZ.toFixed(1)} mm ` +
      `with ${wallThickness}mm wall thickness (minimum dimension: ${(wallThickness * 3).toFixed(1)}mm)`
    );
  }

  // Symmetric XY inset: use the smaller of X/Y to keep walls even
  const minXY = Math.min(dimX, dimY);
  const xyScale = (minXY - wallThickness * 2) / minXY;

  // Z scale: inset from top only (bottom preserved by translate)
  const zScale = (dimZ - wallThickness) / dimZ;

  return {
    scaleX: Math.round(xyScale * 100000) / 100000,
    scaleY: Math.round(xyScale * 100000) / 100000,
    scaleZ: Math.round(zScale * 100000) / 100000
  };
}

/**
 * Repair an STL mesh using admesh (fill holes, fix normals, remove degenerate facets).
 * Returns the path to the repaired file, or the original path if admesh isn't available.
 * @param {string} stlPath - Absolute path to the input STL
 * @param {string} tmpDir  - Temp directory path prefix for repaired file
 * @returns {Promise<{repairedPath: string, wasRepaired: boolean}>}
 */
async function repairStl(stlPath, tmpDir) {
  const repairedPath = tmpDir + '-repaired.stl';
  return new Promise((resolve) => {
    const proc = spawn('admesh', [
      '--fill-holes',
      '--normal-directions',
      '--normal-values',
      '--remove-unconnected',
      '-b', repairedPath,
      stlPath
    ], { timeout: 60000, stdio: ['ignore', 'pipe', 'pipe'] });

    let stderr = '';
    proc.stderr.on('data', (d) => { stderr += d.toString(); });

    proc.on('error', (err) => {
      console.warn('[Hollow] admesh not available, skipping repair:', err.message);
      resolve({ repairedPath: stlPath, wasRepaired: false });
    });

    proc.on('close', (code) => {
      if (code === 0 && fs.existsSync(repairedPath) && fs.statSync(repairedPath).size > 0) {
        console.log('[Hollow] Mesh repaired with admesh');
        resolve({ repairedPath, wasRepaired: true });
      } else {
        console.warn('[Hollow] admesh failed (code', code + '), using original mesh. stderr:', stderr.slice(0, 200));
        resolve({ repairedPath: stlPath, wasRepaired: false });
      }
    });
  });
}

/**
 * Hollow a solid STL file using OpenSCAD boolean subtraction.
 * Automatically repairs non-manifold meshes with admesh before processing.
 *
 * @param {object} opts
 * @param {string} opts.stlPath       - Absolute path to the input STL
 * @param {string} opts.outputPath    - Absolute path for the output hollowed STL
 * @param {number} [opts.wallThickness=2] - Wall thickness in mm
 * @param {object} opts.dimensions    - { x, y, z } bounding box dimensions in mm
 * @returns {Promise<{success: boolean, outputPath?: string, error?: string, stderr?: string}>}
 */
async function hollowStl({ stlPath, outputPath, wallThickness = 2, dimensions }) {
  // Validate inputs
  if (!stlPath || !fs.existsSync(stlPath)) {
    return { success: false, error: `Input STL not found: ${stlPath}` };
  }
  if (!outputPath) {
    return { success: false, error: 'Output path is required' };
  }
  if (!dimensions || !dimensions.x || !dimensions.y || !dimensions.z) {
    return { success: false, error: 'Bounding box dimensions (x, y, z) are required' };
  }
  if (wallThickness <= 0 || wallThickness > 50) {
    return { success: false, error: `Invalid wall thickness: ${wallThickness}mm (must be 0-50mm)` };
  }

  // Compute scale factors
  let scaleX, scaleY, scaleZ;
  try {
    const factors = computeScaleFactors(dimensions.x, dimensions.y, dimensions.z, wallThickness);
    scaleX = factors.scaleX;
    scaleY = factors.scaleY;
    scaleZ = factors.scaleZ;
  } catch (err) {
    return { success: false, error: err.message };
  }

  const tmpId = crypto.randomBytes(8).toString('hex');
  const tmpPrefix = path.join(os.tmpdir(), `hollow-${tmpId}`);
  const scadPath = tmpPrefix + '.scad';
  let repairedPath = null;

  console.log(`[Hollow] Scale factors: X=${scaleX}, Y=${scaleY}, Z=${scaleZ} (wall=${wallThickness}mm)`);
  console.log(`[Hollow] Dimensions: ${dimensions.x} x ${dimensions.y} x ${dimensions.z} mm`);

  try {
    // Step 1: Repair mesh with admesh (fill holes, fix normals)
    const repair = await repairStl(stlPath, tmpPrefix);
    const meshPath = repair.repairedPath;
    if (repair.wasRepaired) repairedPath = repair.repairedPath;

    // Step 2: Generate .scad using the (possibly repaired) mesh
    const scadContent = generateHollowScad(meshPath, scaleX, scaleY, scaleZ, wallThickness);
    fs.writeFileSync(scadPath, scadContent, 'utf-8');

    // Step 3: Ensure output directory exists
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });

    // Step 4: Run OpenSCAD
    const result = await runOpenScad(scadPath, outputPath);

    // Verify output was created
    if (!fs.existsSync(outputPath)) {
      return { success: false, error: 'OpenSCAD completed but output file was not created', stderr: result.stderr };
    }

    const stats = fs.statSync(outputPath);
    if (stats.size === 0) {
      fs.unlinkSync(outputPath);
      return { success: false, error: 'OpenSCAD produced an empty output file', stderr: result.stderr };
    }

    // Log any warnings
    if (result.stderr) {
      console.warn('[Hollow] OpenSCAD warnings:', result.stderr.trim());
    }

    console.log(`[Hollow] Success: ${outputPath} (${(stats.size / 1024).toFixed(1)} KB)`);
    return { success: true, outputPath, fileSize: stats.size, stderr: result.stderr || '' };
  } catch (err) {
    // Clean up failed output
    try { if (fs.existsSync(outputPath)) fs.unlinkSync(outputPath); } catch (_) {}
    return { success: false, error: err.message };
  } finally {
    // Clean up temp files
    try { fs.unlinkSync(scadPath); } catch (_) {}
    if (repairedPath) { try { fs.unlinkSync(repairedPath); } catch (_) {} }
  }
}

module.exports = { hollowStl, computeScaleFactors, getStlDimensions };
