/**
 * Multiboard Mount Merger
 * Performs boolean union of two STL files using OpenSCAD CLI.
 * Accepts a source STL, a mount STL, and a 4x4 transformation matrix (column-major from Three.js).
 * Generates a temporary .scad file, runs OpenSCAD headlessly, returns the output STL path.
 */

const fs = require('fs');
const path = require('path');
const os = require('os');
const crypto = require('crypto');
const { spawn } = require('child_process');

const OPENSCAD_BIN = process.env.OPENSCAD_PATH || 'openscad';
const OPENSCAD_TIMEOUT_MS = 120000; // 2 minutes

/**
 * Transpose a 16-element column-major (Three.js) matrix to row-major (OpenSCAD).
 * Three.js matrixWorld.toArray() returns column-major:
 *   [m00, m10, m20, m30, m01, m11, m21, m31, m02, m12, m22, m32, m03, m13, m23, m33]
 * OpenSCAD multmatrix() expects row-major 4x4 nested array:
 *   [[m00,m01,m02,m03],[m10,m11,m12,m13],[m20,m21,m22,m23],[m30,m31,m32,m33]]
 */
function transposeToRowMajor4x4(colMajor) {
  if (!Array.isArray(colMajor) || colMajor.length !== 16) {
    throw new Error('Transform must be a 16-element array (column-major 4x4 matrix)');
  }
  // colMajor index layout (column-major):
  //  0  4  8  12
  //  1  5  9  13
  //  2  6  10 14
  //  3  7  11 15
  return [
    [colMajor[0], colMajor[4], colMajor[8],  colMajor[12]],
    [colMajor[1], colMajor[5], colMajor[9],  colMajor[13]],
    [colMajor[2], colMajor[6], colMajor[10], colMajor[14]],
    [colMajor[3], colMajor[7], colMajor[11], colMajor[15]]
  ];
}

/**
 * Generate the .scad file content for a boolean union of two STLs.
 */
function generateScad(sourceStlPath, mountStlPath, rowMajorMatrix) {
  const matrixStr = '[' + rowMajorMatrix.map(row => '[' + row.join(',') + ']').join(',') + ']';
  // Escape backslashes in paths for OpenSCAD (Windows compat)
  const srcPath = sourceStlPath.replace(/\\/g, '/');
  const mntPath = mountStlPath.replace(/\\/g, '/');

  return `// Auto-generated by Multiboard Mount Merger
union() {
  import("${srcPath}");
  multmatrix(${matrixStr})
    import("${mntPath}");
}
`;
}

/**
 * Run OpenSCAD headlessly to produce an STL from a .scad file.
 * @returns {Promise<{stdout: string, stderr: string}>}
 */
function runOpenScad(scadPath, outputPath) {
  return new Promise((resolve, reject) => {
    const args = ['-o', outputPath, scadPath];
    const proc = spawn(OPENSCAD_BIN, args, {
      timeout: OPENSCAD_TIMEOUT_MS,
      stdio: ['ignore', 'pipe', 'pipe']
    });

    let stdout = '';
    let stderr = '';
    proc.stdout.on('data', (d) => { stdout += d.toString(); });
    proc.stderr.on('data', (d) => { stderr += d.toString(); });

    proc.on('error', (err) => {
      if (err.code === 'ENOENT') {
        reject(new Error(`OpenSCAD not found at "${OPENSCAD_BIN}". Install with: sudo apt install openscad`));
      } else {
        reject(err);
      }
    });

    proc.on('close', (code) => {
      if (code === 0) {
        resolve({ stdout, stderr });
      } else {
        reject(new Error(`OpenSCAD exited with code ${code}: ${stderr || 'unknown error'}`));
      }
    });
  });
}

/**
 * Merge two STL files using OpenSCAD boolean union.
 *
 * @param {object} opts
 * @param {string} opts.sourceStlPath  - Absolute path to the source STL
 * @param {string} opts.mountStlPath   - Absolute path to the mount STL
 * @param {number[]} opts.transformMatrix4x4 - 16-element column-major matrix from Three.js
 * @param {string} opts.outputPath     - Absolute path for the output STL
 * @returns {Promise<{success: boolean, outputPath?: string, error?: string, stderr?: string}>}
 */
async function mergeStlWithMount({ sourceStlPath, mountStlPath, transformMatrix4x4, outputPath }) {
  // Validate inputs
  if (!sourceStlPath || !fs.existsSync(sourceStlPath)) {
    return { success: false, error: `Source STL not found: ${sourceStlPath}` };
  }
  if (!mountStlPath || !fs.existsSync(mountStlPath)) {
    return { success: false, error: `Mount STL not found: ${mountStlPath}` };
  }
  if (!outputPath) {
    return { success: false, error: 'Output path is required' };
  }

  // Transpose matrix
  let rowMajor;
  try {
    rowMajor = transposeToRowMajor4x4(transformMatrix4x4);
  } catch (err) {
    return { success: false, error: err.message };
  }

  // Generate temporary .scad file
  const tmpId = crypto.randomBytes(8).toString('hex');
  const scadPath = path.join(os.tmpdir(), `merger-${tmpId}.scad`);
  const scadContent = generateScad(sourceStlPath, mountStlPath, rowMajor);

  try {
    fs.writeFileSync(scadPath, scadContent, 'utf-8');

    // Ensure output directory exists
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });

    // Run OpenSCAD
    const result = await runOpenScad(scadPath, outputPath);

    // Verify output was created
    if (!fs.existsSync(outputPath)) {
      return { success: false, error: 'OpenSCAD completed but output file was not created', stderr: result.stderr };
    }

    const stats = fs.statSync(outputPath);
    if (stats.size === 0) {
      fs.unlinkSync(outputPath);
      return { success: false, error: 'OpenSCAD produced an empty output file', stderr: result.stderr };
    }

    // Log any warnings from stderr
    if (result.stderr) {
      console.warn('[Merger] OpenSCAD warnings:', result.stderr.trim());
    }

    return { success: true, outputPath, stderr: result.stderr || '' };
  } catch (err) {
    // Clean up failed output
    try { if (fs.existsSync(outputPath)) fs.unlinkSync(outputPath); } catch (_) {}
    return { success: false, error: err.message };
  } finally {
    // Clean up temp .scad file
    try { fs.unlinkSync(scadPath); } catch (_) {}
  }
}

module.exports = { mergeStlWithMount, transposeToRowMajor4x4 };
