#!/usr/bin/env python3
"""
Veo 3.1 Frame Interpolation — Standalone Helper

Generates a video from a first frame (and optional last frame) using
Google Veo 3.1's video generation/interpolation API.

Usage:
  python3 scripts/veo31-interpolate.py \
    --first-frame /path/to/frame.png \
    --prompt "She turns around to face camera..." \
    --output /path/to/output.mp4 \
    [--last-frame /path/to/last.png] \
    [--duration 8] \
    [--aspect-ratio 9:16]
"""

import os, sys, time, argparse

def load_api_key():
    """Load GEMINI_API_KEY from .env file."""
    env_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '.env')
    if os.path.exists(env_path):
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line.startswith('GEMINI_API_KEY='):
                    return line.split('=', 1)[1]
    # Also check environment
    return os.environ.get('GEMINI_API_KEY')


def main():
    parser = argparse.ArgumentParser(description='Veo 3.1 Frame Interpolation')
    parser.add_argument('--first-frame', required=True, help='Path to first frame image')
    parser.add_argument('--prompt', required=True, help='Motion/scene prompt for the video')
    parser.add_argument('--output', required=True, help='Output video path (.mp4)')
    parser.add_argument('--last-frame', default=None, help='Optional last frame for interpolation')
    parser.add_argument('--duration', type=int, default=8, choices=[4, 5, 6, 7, 8], help='Duration in seconds (default: 8)')
    parser.add_argument('--aspect-ratio', default='9:16', choices=['9:16', '16:9', '1:1'], help='Aspect ratio (default: 9:16)')
    parser.add_argument('--max-retries', type=int, default=5, help='Max retries on rate limit (default: 5)')
    args = parser.parse_args()

    # Validate inputs
    if not os.path.exists(args.first_frame):
        print(f"ERROR: First frame not found: {args.first_frame}", file=sys.stderr)
        sys.exit(1)
    if args.last_frame and not os.path.exists(args.last_frame):
        print(f"ERROR: Last frame not found: {args.last_frame}", file=sys.stderr)
        sys.exit(1)

    # Load API key
    api_key = load_api_key()
    if not api_key:
        print("ERROR: GEMINI_API_KEY not found in .env or environment", file=sys.stderr)
        sys.exit(1)

    # Import google genai (late import so --help works without the package)
    try:
        from google import genai
        from google.genai.types import Image as GenImage, GenerateVideosConfig
    except ImportError:
        print("ERROR: google-genai package not installed. Run: pip install google-genai", file=sys.stderr)
        sys.exit(1)

    client = genai.Client(api_key=api_key)

    # Read frames
    first_bytes = open(args.first_frame, 'rb').read()
    print(f"First frame: {args.first_frame} ({len(first_bytes) // 1024}KB)")

    # Build config
    veo_config = GenerateVideosConfig(
        aspect_ratio=args.aspect_ratio,
        duration_seconds=args.duration,
    )

    # Optional last frame for true interpolation
    if args.last_frame:
        last_bytes = open(args.last_frame, 'rb').read()
        print(f"Last frame: {args.last_frame} ({len(last_bytes) // 1024}KB)")
        mime = 'image/png' if args.last_frame.lower().endswith('.png') else 'image/jpeg'
        veo_config.last_frame = GenImage(image_bytes=last_bytes, mime_type=mime)

    first_mime = 'image/png' if args.first_frame.lower().endswith('.png') else 'image/jpeg'

    # Generate video with rate-limit retries
    print(f"\nSending to Veo 3.1 (duration={args.duration}s, ratio={args.aspect_ratio})...")
    operation = None
    for retry in range(args.max_retries):
        try:
            operation = client.models.generate_videos(
                model="veo-3.1-generate-preview",
                prompt=args.prompt,
                image=GenImage(image_bytes=first_bytes, mime_type=first_mime),
                config=veo_config,
            )
            break
        except Exception as e:
            if '429' in str(e) and retry < args.max_retries - 1:
                wait = 120 * (retry + 1)
                print(f"  Rate limited, waiting {wait}s (retry {retry + 1}/{args.max_retries})...")
                time.sleep(wait)
            else:
                print(f"ERROR: Veo API call failed: {e}", file=sys.stderr)
                sys.exit(2)

    # Poll for completion
    poll = 0
    while not operation.done:
        time.sleep(15)
        operation = client.operations.get(operation)
        poll += 1
        elapsed = poll * 15
        print(f"  Polling... {elapsed}s", end='\r')

    print(f"\nCompleted after {poll * 15}s")

    # Extract video
    if not operation.result or not operation.result.generated_videos:
        print("ERROR: No videos generated by Veo", file=sys.stderr)
        sys.exit(3)

    video_obj = operation.result.generated_videos[0].video
    client.files.download(file=video_obj)

    # Ensure output directory exists
    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)

    video_obj.save(args.output)
    size_kb = os.path.getsize(args.output) // 1024
    print(f"Video saved: {args.output} ({size_kb}KB)")

    # Output JSON result for machine parsing
    import json
    result = {
        "status": "success",
        "output": args.output,
        "duration": args.duration,
        "aspect_ratio": args.aspect_ratio,
        "size_bytes": os.path.getsize(args.output),
        "poll_seconds": poll * 15
    }
    print(f"\n__RESULT_JSON__:{json.dumps(result)}")


if __name__ == '__main__':
    main()
