/**
 * Social Trend Monitor & Auto-Design System
 *
 * Continuously monitors Reddit and Google Trends for viral content,
 * uses Claude AI to evaluate apparel design potential, generates
 * designs via Gemini AI, and auto-lists approved designs to Shopify.
 *
 * Targets: GenX, Millennials, GenZ
 * Style: Sarcastic, witty, comical, playful
 */

const fs = require('fs');
const path = require('path');
const https = require('https');
const crypto = require('crypto');
const ollamaClient = require('../lib/ollama-client');

const DATA_DIR = path.resolve(__dirname, '..', '..', 'data');
const TRENDS_FILE = path.join(DATA_DIR, 'trend-monitor.json');
const HISTORY_FILE = path.join(DATA_DIR, 'trend-monitor-history.json');

// =============================================================================
// DEFAULT SETTINGS
// =============================================================================

const DEFAULT_SETTINGS = {
  scanIntervalHours: 4,
  enabled: true,
  autoGenerateDesigns: true,
  autoListToShopify: false,
  maxTrendsPerScan: 20,
  minScoreForDesign: 65,
  minScoreForAlert: 80,
  notifySms: true,
  notifyEmail: true,
  notifyDesktop: true,
  smsRecipients: (process.env.TREND_ALERT_PHONES || '+18888581105,+12027408240').split(',').map(s => s.trim()).filter(Boolean),
  emailRecipients: [],
  contentFilters: {
    blockSexualAssault: true,
    blockExplicitHate: true,
    allowEdgy: true,
    allowPolitical: true
  },
  targetAudiences: ['genx', 'millennial', 'genz'],
  designStyle: 'sarcastic, witty, comical, playful',
  printMethods: ['dtf', 'vinyl', 'sublimation'],
  shopifyCollectionTitle: 'Trending Designs',
  defaultPriceCents: 2499,
  redditSubreddits: [
    'all', 'popular', 'memes', 'funny', 'me_irl',
    'whitepeopletwitter', 'blackpeopletwitter',
    'starterpacks', 'suspiciouslyspecific', 'oddlyspecific',
    'technicallythetruth', 'brandnewsentence',
    'GenX', 'millennialmemes', 'GenZ'
  ],
  googleTrendsGeo: 'US'
};

// =============================================================================
// DATA PERSISTENCE (JSON file — matches other server/modules/ pattern)
// =============================================================================

function createEmptyData() {
  return {
    settings: { ...DEFAULT_SETTINGS },
    lastScanAt: null,
    scanCount: 0,
    trends: [],
    designs: [],
    stats: {
      totalScans: 0,
      totalTrendsFound: 0,
      totalDesignsGenerated: 0,
      totalApproved: 0,
      totalListed: 0,
      totalRejected: 0
    }
  };
}

function loadData() {
  try {
    if (fs.existsSync(TRENDS_FILE)) {
      return JSON.parse(fs.readFileSync(TRENDS_FILE, 'utf8'));
    }
  } catch (e) {
    console.error('[TrendMonitor] Error loading data:', e.message);
  }
  return createEmptyData();
}

function saveData(data) {
  try {
    fs.mkdirSync(DATA_DIR, { recursive: true });
    const tmp = TRENDS_FILE + '.tmp';
    fs.writeFileSync(tmp, JSON.stringify(data, null, 2));
    fs.renameSync(tmp, TRENDS_FILE);
  } catch (e) {
    console.error('[TrendMonitor] Error saving data:', e.message);
  }
}

function loadHistory() {
  try {
    if (fs.existsSync(HISTORY_FILE)) {
      return JSON.parse(fs.readFileSync(HISTORY_FILE, 'utf8'));
    }
  } catch (e) {
    console.error('[TrendMonitor] Error loading history:', e.message);
  }
  return { archivedTrends: [], archivedDesigns: [] };
}

function saveHistory(history) {
  try {
    fs.mkdirSync(DATA_DIR, { recursive: true });
    // Cap both arrays to prevent unbounded growth
    if (history.archivedTrends && history.archivedTrends.length > 500) {
      history.archivedTrends = history.archivedTrends.slice(-500);
    }
    if (history.archivedDesigns && history.archivedDesigns.length > 500) {
      history.archivedDesigns = history.archivedDesigns.slice(-500);
    }
    const tmp = HISTORY_FILE + '.tmp';
    fs.writeFileSync(tmp, JSON.stringify(history, null, 2));
    fs.renameSync(tmp, HISTORY_FILE);
  } catch (e) {
    console.error('[TrendMonitor] Error saving history:', e.message);
  }
}

// =============================================================================
// HTTP HELPER (raw https — matches sms.js and shopify.js pattern)
// =============================================================================

function httpGet(url, headers = {}, _retries = 0) {
  return new Promise((resolve, reject) => {
    const u = new URL(url);
    const opts = {
      hostname: u.hostname,
      port: u.port || 443,
      path: u.pathname + (u.search || ''),
      method: 'GET',
      headers: {
        'Accept': 'application/json',
        'User-Agent': 'TrendMonitor/1.0 (SwayzCustomVinyl)',
        ...headers
      }
    };

    const protocol = u.protocol === 'http:' ? require('http') : https;
    const req = protocol.request(opts, (res) => {
      // Handle 429 Too Many Requests with exponential backoff
      if (res.statusCode === 429 && _retries < 3) {
        const retryAfter = parseInt(res.headers['retry-after'] || '0', 10);
        const backoffMs = Math.max(retryAfter * 1000, Math.pow(2, _retries + 1) * 1000);
        console.warn(`[TrendMonitor] 429 rate limited by ${u.hostname}, retrying in ${backoffMs}ms (attempt ${_retries + 1}/3)`);
        res.resume(); // drain response
        setTimeout(() => {
          httpGet(url, headers, _retries + 1).then(resolve).catch(reject);
        }, backoffMs);
        return;
      }
      const chunks = [];
      res.on('data', c => chunks.push(c));
      res.on('end', () => {
        const text = Buffer.concat(chunks).toString('utf8');
        try {
          resolve(JSON.parse(text));
        } catch (_) {
          resolve(text);
        }
      });
    });
    req.on('error', reject);
    req.setTimeout(30000, () => {
      req.destroy(new Error('Request timeout'));
    });
    req.end();
  });
}

// =============================================================================
// REDDIT CLIENT (RSS feeds — works from datacenter IPs unlike JSON API)
// =============================================================================

function parseAtomFeed(xml) {
  // Lightweight Atom XML parser for Reddit RSS
  const entries = [];
  const entryRegex = /<entry>([\s\S]*?)<\/entry>/g;
  let match;
  while ((match = entryRegex.exec(xml)) !== null) {
    const block = match[1];
    const get = (tag) => {
      const m = block.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)<\\/${tag}>`));
      return m ? m[1].replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&#39;/g, "'").replace(/&quot;/g, '"').trim() : '';
    };
    const linkMatch = block.match(/<link[^>]+href="([^"]+)"/);
    const idMatch = block.match(/<id>([^<]*)<\/id>/);

    entries.push({
      title: get('title'),
      link: linkMatch ? linkMatch[1] : '',
      content: get('content'),
      id: idMatch ? idMatch[1] : '',
      updated: get('updated'),
      category: (block.match(/<category[^>]+term="([^"]+)"/) || [])[1] || ''
    });
  }
  return entries;
}

async function fetchRedditTrends(subreddits, limit = 10) {
  const trends = [];
  const seen = new Set();

  for (const sub of subreddits) {
    try {
      const url = `https://www.reddit.com/r/${encodeURIComponent(sub)}/hot.rss?limit=${limit}`;
      const xml = await httpGet(url);

      if (typeof xml !== 'string' || !xml.includes('<entry>')) continue;

      const entries = parseAtomFeed(xml);

      for (const entry of entries) {
        if (!entry.title) continue;

        // Extract post ID from link or id field
        const idMatch = (entry.link || entry.id || '').match(/comments\/([a-z0-9]+)/);
        const postId = idMatch ? idMatch[1] : crypto.createHash('md5').update(entry.title).digest('hex').slice(0, 10);

        if (seen.has(postId)) continue;
        seen.add(postId);

        // Try to extract upvote count from content HTML (Reddit includes it in some feeds)
        const scoreMatch = (entry.content || '').match(/(\d[\d,]+)\s*(?:points?|upvotes?)/i);
        const upvotes = scoreMatch ? parseInt(scoreMatch[1].replace(/,/g, ''), 10) : null;

        trends.push({
          id: `reddit_${postId}`,
          source: 'reddit',
          sourceId: postId,
          title: entry.title.slice(0, 300),
          snippet: (entry.content || '').replace(/<[^>]+>/g, '').slice(0, 200),
          url: entry.link || `https://reddit.com/r/${sub}`,
          subreddit: entry.category || sub,
          upvotes: upvotes,
          comments: null,
          searchVolume: null,
          relatedQueries: [],
          createdUtc: entry.updated ? Math.floor(new Date(entry.updated).getTime() / 1000) : null
        });
      }

      // Rate limit: 1 req/sec
      await new Promise(r => setTimeout(r, 1200));
    } catch (err) {
      console.error(`[TrendMonitor] Reddit RSS error for r/${sub}:`, err.message);
    }
  }

  return trends;
}

// =============================================================================
// GOOGLE TRENDS CLIENT (RSS feed — works from datacenter IPs)
// =============================================================================

function parseRssFeed(xml) {
  const items = [];
  const itemRegex = /<item>([\s\S]*?)<\/item>/g;
  let match;
  while ((match = itemRegex.exec(xml)) !== null) {
    const block = match[1];
    const get = (tag) => {
      const m = block.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)<\\/${tag}>`));
      return m ? m[1].replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, '$1').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').trim() : '';
    };
    items.push({
      title: get('title'),
      link: get('link'),
      description: get('description'),
      pubDate: get('pubDate'),
      traffic: get('ht:approx_traffic') || get('ht:picture_source')
    });
  }
  return items;
}

async function fetchGoogleTrends(geo = 'US') {
  const trends = [];

  try {
    const url = `https://trends.google.com/trending/rss?geo=${encodeURIComponent(geo)}`;
    const xml = await httpGet(url);

    if (typeof xml !== 'string' || !xml.includes('<item>')) {
      console.error('[TrendMonitor] Google Trends RSS: unexpected response');
      return trends;
    }

    const items = parseRssFeed(xml);

    for (const item of items) {
      const title = item.title;
      if (!title) continue;

      // Parse related news from description HTML
      const newsMatch = (item.description || '').match(/<a[^>]+href="([^"]+)"[^>]*>([^<]+)<\/a>/);
      const newsTitle = newsMatch ? newsMatch[2] : '';
      const newsUrl = newsMatch ? newsMatch[1] : '';

      trends.push({
        id: `google_${crypto.createHash('md5').update(title).digest('hex').slice(0, 12)}`,
        source: 'google_trends',
        sourceId: title,
        title: title,
        snippet: newsTitle.slice(0, 200),
        url: newsUrl || `https://trends.google.com/trends/explore?q=${encodeURIComponent(title)}&geo=${geo}`,
        subreddit: null,
        upvotes: null,
        comments: null,
        searchVolume: item.traffic || null,
        relatedQueries: []
      });
    }
  } catch (err) {
    console.error('[TrendMonitor] Google Trends error:', err.message);
  }

  return trends;
}

// =============================================================================
// TREND SCORING ALGORITHM
// =============================================================================

const SCORE_WEIGHTS = {
  virality: 0.20,
  humorPotential: 0.30,
  apparelRelevance: 0.25,
  audienceMatch: 0.15,
  timeliness: 0.10
};

function calculateCompositeScore(breakdown) {
  let score = 0;
  for (const [key, weight] of Object.entries(SCORE_WEIGHTS)) {
    score += (breakdown[key] || 0) * weight;
  }
  return Math.round(score);
}

// =============================================================================
// CLAUDE AI TREND ANALYSIS
// =============================================================================

async function analyzeTrendsWithClaude(rawTrends, settings) {
  if (!rawTrends.length) return [];

  const systemPrompt = `You are a trend-to-apparel design analyst for a print-on-demand business.
Evaluate social media trends for sarcastic/witty/comical t-shirt design potential.
Target: GenX, Millennials, GenZ. Style: ${settings.designStyle}.
Print: DTF (full color), Vinyl (solid colors, text), Sublimation (all-over).
Rules: BLOCK sexual assault references. Edgy/political/dark humor OK.

ONLY return items that WOULD make good apparel. Skip the rest entirely.

For each good trend return a JSON object:
{"originalTitle":"...","isGoodForApparel":true,"scoreBreakdown":{"virality":0-100,"humorPotential":0-100,"apparelRelevance":0-100,"audienceMatch":0-100,"timeliness":0-100},"reasoning":"1 sentence","suggestedPhrases":["phrase1","phrase2"],"suggestedVisuals":["visual desc"],"targetAudience":"genx|millennial|genz|all","humorStyle":"sarcastic|witty|absurdist|deadpan|nostalgic|self-deprecating","printMethodRecommendation":"dtf|vinyl|sublimation"}

Return ONLY a JSON array. No markdown fences, no explanation, no text outside the array.`;

  // Process in batches of 15 to avoid token limits
  const BATCH_SIZE = 15;
  const allAnalyzed = [];
  const trendsToAnalyze = rawTrends.slice(0, 60); // Cap at 60 total

  for (let i = 0; i < trendsToAnalyze.length; i += BATCH_SIZE) {
    const batch = trendsToAnalyze.slice(i, i + BATCH_SIZE);
    const batchData = batch.map(t => ({
      title: t.title.slice(0, 150),
      source: t.source,
      snippet: (t.snippet || '').slice(0, 100),
      subreddit: t.subreddit || null
    }));

    try {
      const batchNum = Math.floor(i / BATCH_SIZE) + 1;
      const totalBatches = Math.ceil(trendsToAnalyze.length / BATCH_SIZE);
      console.log(`[TrendMonitor] Ollama batch ${batchNum}/${totalBatches} (${batchData.length} trends)...`);

      const messages = [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: `Evaluate these ${batchData.length} trends. Only return the ones good for t-shirts:\n${JSON.stringify(batchData)}` }
      ];

      const text = await ollamaClient.chat(messages, { temperature: 0.5, timeout: 180000 });
      const cleaned = text.replace(/^```json?\s*/i, '').replace(/```\s*$/i, '').trim();
      const results = JSON.parse(cleaned);

      if (!Array.isArray(results)) continue;

      // Merge results back into raw trends
      for (const raw of batch) {
        const match = results.find(r =>
          r.originalTitle === raw.title ||
          r.originalTitle?.toLowerCase() === raw.title?.toLowerCase() ||
          raw.title?.toLowerCase().includes((r.originalTitle || '').toLowerCase().slice(0, 40))
        );

        if (match && match.isGoodForApparel) {
          const scoreBreakdown = match.scoreBreakdown || {};
          allAnalyzed.push({
            ...raw,
            score: calculateCompositeScore(scoreBreakdown),
            scoreBreakdown,
            aiAnalysis: {
              isGoodForApparel: true,
              reasoning: match.reasoning || '',
              suggestedPhrases: match.suggestedPhrases || [],
              suggestedVisuals: match.suggestedVisuals || [],
              targetAudience: match.targetAudience || 'all',
              humorStyle: match.humorStyle || 'witty',
              printMethodRecommendation: match.printMethodRecommendation || 'dtf'
            },
            status: 'new',
            discoveredAt: new Date().toISOString(),
            expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString()
          });
        }
      }
    } catch (err) {
      console.error(`[TrendMonitor] Ollama batch ${Math.floor(i / BATCH_SIZE) + 1} error:`, err.message);
    }
  }

  console.log(`[TrendMonitor] Ollama analysis complete: ${allAnalyzed.length} trends qualify for apparel`);
  return allAnalyzed;
}

// =============================================================================
// CONTENT FILTER
// =============================================================================

const BLOCKED_PATTERNS = [
  /sexual\s*assault/i, /rape\s*joke/i, /non-?consensual/i,
  /child\s*(abuse|exploitation)/i, /pedophil/i
];

function passesContentFilter(text, settings) {
  const combined = String(text || '');
  for (const pattern of BLOCKED_PATTERNS) {
    if (pattern.test(combined)) return false;
  }
  return true;
}

// =============================================================================
// DESIGN GENERATION (uses Gemini AI workflow)
// =============================================================================

const PRINT_METHOD_INSTRUCTIONS = {
  dtf: 'full color design, suitable for DTF print transfer, vibrant colors, transparent or solid background, no mockup',
  vinyl: 'bold single or dual-color design, suitable for vinyl heat transfer, clean lines, solid fills, vector-style, no gradients',
  sublimation: 'all-over print design, edge-to-edge coverage, vibrant full-color, sublimation ready, seamless pattern elements'
};

function buildApparelPrompt(phrase, visualConcept, printMethod) {
  const method = PRINT_METHOD_INSTRUCTIONS[printMethod] || PRINT_METHOD_INSTRUCTIONS.dtf;
  return `T-shirt graphic design: "${phrase}". ${visualConcept}. ${method}. Isolated design only, print-ready, high contrast, bold typography, no human models, no clothing mockup`;
}

async function generateDesignForTrend(trend, settings) {
  const { NanoBananaWorkflow, MODELS } = require('../nano-banana-workflow');
  const workflow = new NanoBananaWorkflow();
  const designs = [];

  const phrases = (trend.aiAnalysis.suggestedPhrases || []).slice(0, 2);
  const visual = (trend.aiAnalysis.suggestedVisuals || [])[0] || 'bold retro typography with distressed texture';
  const printMethod = trend.aiAnalysis.printMethodRecommendation || 'dtf';

  for (const phrase of phrases) {
    if (!passesContentFilter(phrase, settings)) continue;

    const promptKeywords = buildApparelPrompt(phrase, visual, printMethod);

    try {
      const result = await workflow.runWithPrompt(promptKeywords, {
        aspectRatio: '1:1',
        numImages: 2,
        model: MODELS.GEMINI_2_FLASH,
        category: 'products/apparel',
        addToArtwork: false
      });

      if (result.success && result.images) {
        for (const image of result.images) {
          designs.push({
            id: `design_${crypto.randomUUID().slice(0, 12)}`,
            trendId: trend.id,
            phrase,
            visualDescription: visual,
            aiPrompt: promptKeywords,
            aiGenerationId: image.generationId || null,
            imagePath: `/images/ai-generated/text-to-image/${image.filename}`,
            imageFilename: image.filename,
            imageUrl: image.url || null,
            status: 'pending',
            printMethod,
            shopifyProductId: null,
            shopifyProductUrl: null,
            createdAt: new Date().toISOString(),
            approvedAt: null,
            listedAt: null,
            listingData: null
          });
        }
      }
    } catch (err) {
      console.error(`[TrendMonitor] Design generation failed for "${phrase}":`, err.message);
    }
  }

  return designs;
}

// =============================================================================
// TIKTOK SHOP CAPACITY HELPER
// =============================================================================

/**
 * Determine if a product should be published to TikTok Shop based on capacity and type.
 * @param {string} productType - e.g. 'T-Shirt', 'Metal Print', 'Multiboard'
 * @param {object} capacity - { current, max, available }
 * @returns {{ publish: boolean, reason: string }}
 */
function shouldPublishToTikTok(productType, capacity) {
  if (!capacity || capacity.available <= 0) {
    return { publish: false, reason: `TikTok Shop full (${capacity?.current || '?'}/${capacity?.max || 100})` };
  }

  const type = (productType || '').toLowerCase();
  const preferred = ['metal print', 'metal art', 'multiboard', 'wall organizer'];
  const acceptable = ['t-shirt', 'tshirt'];

  const isPreferred = preferred.some(p => type.includes(p));
  const isAcceptable = acceptable.some(a => type.includes(a));

  // Always publish preferred categories
  if (isPreferred) {
    return { publish: true, reason: `Preferred category for TikTok (${capacity.current}/${capacity.max})` };
  }

  // Publish acceptable categories if there's decent room (>10 slots)
  if (isAcceptable && capacity.available > 10) {
    return { publish: true, reason: `Acceptable category, room available (${capacity.current}/${capacity.max})` };
  }

  // Trending t-shirts get in if there's room (>20 slots)
  if (isAcceptable && capacity.available > 20) {
    return { publish: true, reason: `Trending tee, good capacity (${capacity.current}/${capacity.max})` };
  }

  return { publish: false, reason: `Category not prioritized for TikTok or low capacity (${capacity.current}/${capacity.max})` };
}

// SHOPIFY AUTO-LISTING (uses existing Shopify + listing optimizer)
// =============================================================================

async function listDesignToShopify(design, trend, settings) {
  const shopify = require('../integrations/shopify');

  if (!shopify.isConfigured()) {
    throw new Error('Shopify not configured');
  }

  const basePriceDollars = (settings.defaultPriceCents / 100).toFixed(2);
  const xlPrice = ((settings.defaultPriceCents + 200) / 100).toFixed(2);
  const xxlPrice = ((settings.defaultPriceCents + 400) / 100).toFixed(2);

  const tags = [
    'trending', 'trend-monitor', 'auto-generated',
    trend.aiAnalysis?.targetAudience || 'all',
    trend.aiAnalysis?.humorStyle || 'witty',
    design.printMethod || 'dtf'
  ].join(', ');

  const descriptionHtml = `<p>${design.phrase}</p>
<p><strong>Style:</strong> ${trend.aiAnalysis?.humorStyle || 'witty'} humor</p>
<ul>
<li>Premium quality ${design.printMethod?.toUpperCase() || 'DTF'} print</li>
<li>Available in sizes S-2XL</li>
<li>Machine washable</li>
<li>Unisex fit</li>
</ul>
<p><em>Inspired by what's trending right now.</em></p>`;

  const product = {
    title: design.phrase.slice(0, 255),
    body_html: descriptionHtml,
    tags,
    product_type: 'T-Shirt',
    vendor: 'BlueRidgeCustomCo',
    variants: [
      { option1: 'S', price: basePriceDollars, sku: `TREND-${design.id}-S`, inventory_management: null },
      { option1: 'M', price: basePriceDollars, sku: `TREND-${design.id}-M`, inventory_management: null },
      { option1: 'L', price: basePriceDollars, sku: `TREND-${design.id}-L`, inventory_management: null },
      { option1: 'XL', price: xlPrice, sku: `TREND-${design.id}-XL`, inventory_management: null },
      { option1: '2XL', price: xxlPrice, sku: `TREND-${design.id}-2XL`, inventory_management: null }
    ],
    options: [{ name: 'Size', values: ['S', 'M', 'L', 'XL', '2XL'] }],
    status: 'active'
  };

  // Create the product
  const created = await shopify.createProduct(product);
  console.log(`[TrendMonitor] Shopify product created: ${created.id}`);

  // Add the design image
  const imagePath = path.join(__dirname, '..', '..', 'web', design.imagePath);
  if (fs.existsSync(imagePath)) {
    const imageBase64 = fs.readFileSync(imagePath).toString('base64');
    await shopify.addProductImage(created.id, {
      attachment: imageBase64,
      filename: design.imageFilename,
      alt: design.phrase
    });
  } else if (design.imageUrl) {
    await shopify.addProductImage(created.id, {
      src: design.imageUrl,
      alt: design.phrase
    });
  }

  // Find or create the trending collection
  let collection = await shopify.findCustomCollectionByTitle(settings.shopifyCollectionTitle);
  if (!collection) {
    collection = await shopify.createCustomCollection(settings.shopifyCollectionTitle, {
      body_html: '<p>Hot trending designs fresh from social media. Limited availability!</p>'
    });
    console.log(`[TrendMonitor] Created Shopify collection: ${settings.shopifyCollectionTitle}`);
  }

  if (collection?.id) {
    await shopify.addProductToCollection(created.id, collection.id);
  }

  // Publish to sales channels — with TikTok capacity awareness
  try {
    // First, publish to all channels
    await shopify.publishEverywhere(created.id);

    // Then check TikTok capacity and unpublish if needed
    const tiktokPub = await shopify.findTikTokPublication();
    if (tiktokPub) {
      const tiktokProducts = await shopify.getProductsOnPublication(tiktokPub.id);
      const capacity = { current: tiktokProducts.length, max: 100, available: Math.max(0, 100 - tiktokProducts.length) };
      const tiktokDecision = shouldPublishToTikTok(product.product_type, capacity);

      if (!tiktokDecision.publish) {
        await shopify.unpublishFromPublication(created.id, [tiktokPub.id]);
        console.log(`[TrendMonitor] TikTok Shop at ${capacity.current}/100 — skipped: ${tiktokDecision.reason}`);
      } else {
        console.log(`[TrendMonitor] TikTok Shop at ${capacity.current}/100 — published: ${tiktokDecision.reason}`);
      }
    }
  } catch (err) {
    console.error('[TrendMonitor] Publish error (non-fatal):', err.message);
  }

  return {
    shopifyProductId: created.id,
    shopifyProductUrl: created.handle
      ? `https://${process.env.SHOPIFY_STORE_DOMAIN || 'store'}/products/${created.handle}`
      : null
  };
}

// =============================================================================
// NOTIFICATIONS (uses existing SMS + email)
// =============================================================================

async function sendTrendAlerts(trends, settings) {
  const trendSummary = trends.map(t =>
    `[${t.score}] ${t.title} (${t.source})`
  ).join('\n');

  // SMS
  if (settings.notifySms) {
    try {
      const sms = require('../sms');
      if (sms.isConfigured()) {
        const body = `[TrendMonitor] ${trends.length} hot trend(s)!\n\n${trendSummary.slice(0, 300)}`;
        await sms.sendBulkSms({
          to: settings.smsRecipients,
          body
        });
        console.log(`[TrendMonitor] SMS alert sent to ${settings.smsRecipients.length} recipient(s)`);
      }
    } catch (err) {
      console.error('[TrendMonitor] SMS alert error:', err.message);
    }
  }

  // Email
  if (settings.notifyEmail && settings.emailRecipients?.length) {
    try {
      const { sendOrdersEmail } = require('../mailer');
      const html = buildTrendAlertEmail(trends);
      for (const email of settings.emailRecipients) {
        await sendOrdersEmail({
          to: email,
          subject: `[TrendMonitor] ${trends.length} Hot Trend(s) Found`,
          text: trendSummary,
          html
        });
      }
      console.log(`[TrendMonitor] Email alert sent to ${settings.emailRecipients.length} recipient(s)`);
    } catch (err) {
      console.error('[TrendMonitor] Email alert error:', err.message);
    }
  }
}

function buildTrendAlertEmail(trends) {
  const rows = trends.map(t => {
    const color = t.score >= 90 ? '#22c55e' : t.score >= 80 ? '#f59e0b' : '#3b82f6';
    const phrases = (t.aiAnalysis?.suggestedPhrases || []).slice(0, 2).join(' | ');
    return `
      <div style="background:#f8fafc;padding:15px;border-radius:8px;margin:10px 0;border-left:4px solid ${color};">
        <strong style="font-size:1.1em;">${t.title}</strong><br>
        <span style="color:#64748b;">Score: ${t.score} | Source: ${t.source}${t.subreddit ? ` (r/${t.subreddit})` : ''} | Audience: ${t.aiAnalysis?.targetAudience || 'all'}</span><br>
        ${phrases ? `<em style="color:#475569;">Phrases: ${phrases}</em>` : ''}
      </div>`;
  }).join('');

  return `
    <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;">
      <h2 style="color:#2563eb;">Trending Now</h2>
      <p>${trends.length} trend(s) scored above your alert threshold:</p>
      ${rows}
      <p style="margin-top:20px;">
        <a href="#" style="display:inline-block;background:#2563eb;color:white;padding:12px 24px;text-decoration:none;border-radius:6px;">Open Print Station to Review</a>
      </p>
      <p style="color:#94a3b8;font-size:0.85em;">Sent by Trend Monitor | BlueRidgeCustomCo</p>
    </div>`.trim();
}

// =============================================================================
// SCAN ORCHESTRATOR
// =============================================================================

let _scanRunning = false;

async function runTrendScan(settings) {
  if (_scanRunning) {
    console.log('[TrendMonitor] Scan already in progress, skipping');
    return [];
  }
  _scanRunning = true;

  console.log('[TrendMonitor] Starting trend scan...');
  const scanStart = Date.now();

  try {
    // Step 1: Fetch raw trends
    console.log('[TrendMonitor] Fetching Reddit trends...');
    const redditTrends = await fetchRedditTrends(
      settings.redditSubreddits || DEFAULT_SETTINGS.redditSubreddits,
      settings.maxTrendsPerScan || 20
    );
    console.log(`[TrendMonitor] Reddit: ${redditTrends.length} posts found`);

    console.log('[TrendMonitor] Fetching Google Trends...');
    const googleTrendResults = await fetchGoogleTrends(settings.googleTrendsGeo || 'US');
    console.log(`[TrendMonitor] Google: ${googleTrendResults.length} trends found`);

    // Step 2: Merge and deduplicate
    const allRaw = deduplicateTrends([...redditTrends, ...googleTrendResults]);
    console.log(`[TrendMonitor] ${allRaw.length} unique trends after dedup`);

    if (allRaw.length === 0) {
      console.log('[TrendMonitor] No trends found this scan');
      _scanRunning = false;
      return [];
    }

    // Step 3: Claude AI analysis and scoring
    console.log('[TrendMonitor] Analyzing trends with Claude...');
    const analyzed = await analyzeTrendsWithClaude(allRaw, settings);
    console.log(`[TrendMonitor] ${analyzed.length} trends scored above design threshold`);

    // Step 4: Filter content
    const filtered = analyzed.filter(t =>
      passesContentFilter(t.title + ' ' + (t.aiAnalysis?.suggestedPhrases || []).join(' '), settings)
    );

    // Step 5: Save trends to data store (merge with existing, avoid duplicates)
    const data = loadData();
    const existingIds = new Set(data.trends.map(t => t.id));
    let newCount = 0;

    for (const trend of filtered) {
      if (!existingIds.has(trend.id)) {
        data.trends.push(trend);
        existingIds.add(trend.id);
        newCount++;
      }
    }

    // Step 6: Generate designs for high-scoring new trends
    if (settings.autoGenerateDesigns) {
      const designTrends = filtered.filter(t => t.score >= (settings.minScoreForDesign || 65));
      console.log(`[TrendMonitor] Generating designs for ${designTrends.length} trend(s)...`);

      for (const trend of designTrends) {
        // Auto-generation disabled — costs too much on Gemini API.
        // Trends are still tracked; designs can be generated manually from the UI.
        // Skip if designs already exist for this trend
        if (data.designs.some(d => d.trendId === trend.id)) continue;
        console.log(`[TrendMonitor] Trend logged (no auto-generate): ${trend.title.slice(0, 60)}`);
      }
    }

    // Step 7: Send alerts for high-scoring trends
    const alertTrends = filtered.filter(t => t.score >= (settings.minScoreForAlert || 80));
    if (alertTrends.length > 0) {
      await sendTrendAlerts(alertTrends, settings);
    }

    // Step 8: Update stats and save
    data.lastScanAt = new Date().toISOString();
    data.scanCount++;
    data.stats.totalScans++;
    data.stats.totalTrendsFound += newCount;
    saveData(data);

    const elapsed = ((Date.now() - scanStart) / 1000).toFixed(1);
    console.log(`[TrendMonitor] Scan complete: ${newCount} new trends, ${filtered.length} total qualifying, ${elapsed}s elapsed`);

    return filtered;
  } catch (err) {
    console.error('[TrendMonitor] Scan error:', err.message);
    return [];
  } finally {
    _scanRunning = false;
  }
}

function deduplicateTrends(trends) {
  const seen = new Set();
  return trends.filter(t => {
    const key = t.title.toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 60);
    if (seen.has(key) || seen.has(t.id)) return false;
    seen.add(key);
    seen.add(t.id);
    return true;
  });
}

// =============================================================================
// TREND MANAGEMENT HELPERS
// =============================================================================

function archiveTrend(trendId) {
  const data = loadData();
  const idx = data.trends.findIndex(t => t.id === trendId);
  if (idx < 0) return false;

  const trend = data.trends.splice(idx, 1)[0];
  trend.status = 'archived';

  const history = loadHistory();
  history.archivedTrends.push(trend);
  // Keep last 500 archived trends
  if (history.archivedTrends.length > 500) {
    history.archivedTrends = history.archivedTrends.slice(-500);
  }
  saveHistory(history);
  saveData(data);
  return true;
}

function approveDesign(designId) {
  const data = loadData();
  const design = data.designs.find(d => d.id === designId);
  if (!design) return null;

  design.status = 'approved';
  design.approvedAt = new Date().toISOString();
  data.stats.totalApproved++;
  saveData(data);
  return design;
}

function rejectDesign(designId) {
  const data = loadData();
  const design = data.designs.find(d => d.id === designId);
  if (!design) return null;

  design.status = 'rejected';
  data.stats.totalRejected++;
  saveData(data);
  return design;
}

async function listApprovedDesign(designId) {
  const data = loadData();
  const design = data.designs.find(d => d.id === designId);
  if (!design) throw new Error('Design not found');
  if (design.status !== 'approved') throw new Error('Design must be approved before listing');

  const trend = data.trends.find(t => t.id === design.trendId) || { title: design.phrase, aiAnalysis: {} };
  const settings = data.settings || DEFAULT_SETTINGS;

  const shopifyResult = await listDesignToShopify(design, trend, settings);

  design.status = 'listed';
  design.listedAt = new Date().toISOString();
  design.shopifyProductId = shopifyResult.shopifyProductId;
  design.shopifyProductUrl = shopifyResult.shopifyProductUrl;
  data.stats.totalListed++;
  saveData(data);

  return design;
}

// =============================================================================
// ROUTE HANDLER (matches listing-optimizer.js pattern)
// =============================================================================

function handleTrendMonitorRoute(req, res, parsedUrl, sendJson, db) {
  const pathname = parsedUrl.pathname;

  // GET /api/trends/ — list current trends
  if ((pathname === '/api/trends/' || pathname === '/api/trends') && req.method === 'GET') {
    const data = loadData();
    const status = parsedUrl.searchParams?.get('status');
    let trends = data.trends || [];
    if (status && status !== 'all') {
      trends = trends.filter(t => t.status === status);
    }
    trends.sort((a, b) => (b.score || 0) - (a.score || 0));
    sendJson(res, {
      trends,
      lastScanAt: data.lastScanAt,
      totalCount: trends.length
    });
    return true;
  }

  // GET /api/trends/designs — list designs
  if (pathname === '/api/trends/designs' && req.method === 'GET') {
    const data = loadData();
    const status = parsedUrl.searchParams?.get('status');
    let designs = data.designs || [];
    if (status && status !== 'all') {
      designs = designs.filter(d => d.status === status);
    }
    designs.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
    sendJson(res, { designs, totalCount: designs.length });
    return true;
  }

  // GET /api/trends/settings — get settings
  if (pathname === '/api/trends/settings' && req.method === 'GET') {
    const data = loadData();
    sendJson(res, data.settings || DEFAULT_SETTINGS);
    return true;
  }

  // PUT /api/trends/settings — update settings
  if (pathname === '/api/trends/settings' && req.method === 'PUT') {
    let body = '';
    req.on('data', chunk => body += chunk);
    req.on('end', () => {
      try {
        const updates = JSON.parse(body);
        const data = loadData();
        data.settings = { ...data.settings, ...updates };
        saveData(data);
        sendJson(res, { ok: true, settings: data.settings });
      } catch (err) {
        sendJson(res, { error: err.message }, 400);
      }
    });
    return true;
  }

  // GET /api/trends/stats — aggregate stats
  if (pathname === '/api/trends/stats' && req.method === 'GET') {
    const data = loadData();
    const pendingDesigns = (data.designs || []).filter(d => d.status === 'pending').length;
    const approvedDesigns = (data.designs || []).filter(d => d.status === 'approved').length;
    sendJson(res, {
      ...data.stats,
      lastScanAt: data.lastScanAt,
      scanCount: data.scanCount,
      activeTrends: (data.trends || []).length,
      pendingDesigns,
      approvedDesigns,
      scanRunning: _scanRunning
    });
    return true;
  }

  // GET /api/trends/history — archived trends
  if (pathname === '/api/trends/history' && req.method === 'GET') {
    const history = loadHistory();
    const limit = parseInt(parsedUrl.searchParams?.get('limit') || '50', 10);
    sendJson(res, {
      trends: (history.archivedTrends || []).slice(-limit).reverse(),
      designs: (history.archivedDesigns || []).slice(-limit).reverse()
    });
    return true;
  }

  // POST /api/trends/scan — trigger manual scan
  if (pathname === '/api/trends/scan' && req.method === 'POST') {
    if (_scanRunning) {
      sendJson(res, { ok: false, message: 'Scan already in progress' });
      return true;
    }
    const data = loadData();
    const settings = data.settings || DEFAULT_SETTINGS;
    // Run async — respond immediately
    runTrendScan(settings).then(results => {
      console.log(`[TrendMonitor] Manual scan completed: ${results.length} trends`);
    }).catch(err => {
      console.error('[TrendMonitor] Manual scan failed:', err.message);
    });
    sendJson(res, { ok: true, message: 'Scan started' });
    return true;
  }

  // POST /api/trends/designs/:id/approve
  const approveMatch = pathname.match(/^\/api\/trends\/designs\/([^/]+)\/approve$/);
  if (approveMatch && req.method === 'POST') {
    const design = approveDesign(approveMatch[1]);
    if (design) {
      sendJson(res, { ok: true, design });
    } else {
      sendJson(res, { error: 'Design not found' }, 404);
    }
    return true;
  }

  // POST /api/trends/designs/:id/reject
  const rejectMatch = pathname.match(/^\/api\/trends\/designs\/([^/]+)\/reject$/);
  if (rejectMatch && req.method === 'POST') {
    const design = rejectDesign(rejectMatch[1]);
    if (design) {
      sendJson(res, { ok: true, design });
    } else {
      sendJson(res, { error: 'Design not found' }, 404);
    }
    return true;
  }

  // POST /api/trends/designs/:id/regenerate
  const regenMatch = pathname.match(/^\/api\/trends\/designs\/([^/]+)\/regenerate$/);
  if (regenMatch && req.method === 'POST') {
    const data = loadData();
    const design = data.designs.find(d => d.id === regenMatch[1]);
    if (!design) {
      sendJson(res, { error: 'Design not found' }, 404);
      return true;
    }
    const trend = data.trends.find(t => t.id === design.trendId);
    if (!trend) {
      sendJson(res, { error: 'Associated trend not found' }, 404);
      return true;
    }
    // Run async
    generateDesignForTrend(trend, data.settings || DEFAULT_SETTINGS).then(newDesigns => {
      const d = loadData();
      // Mark old design as rejected
      const old = d.designs.find(dd => dd.id === design.id);
      if (old) old.status = 'rejected';
      d.designs.push(...newDesigns);
      d.stats.totalDesignsGenerated += newDesigns.length;
      saveData(d);
      console.log(`[TrendMonitor] Regenerated ${newDesigns.length} design(s) for trend ${trend.id}`);
    }).catch(err => {
      console.error('[TrendMonitor] Regeneration failed:', err.message);
    });
    sendJson(res, { ok: true, message: 'Regeneration started' });
    return true;
  }

  // POST /api/trends/designs/:id/list — list to Shopify
  const listMatch = pathname.match(/^\/api\/trends\/designs\/([^/]+)\/list$/);
  if (listMatch && req.method === 'POST') {
    const designId = listMatch[1];
    listApprovedDesign(designId).then(design => {
      console.log(`[TrendMonitor] Design ${designId} listed to Shopify: ${design.shopifyProductId}`);
    }).catch(err => {
      console.error(`[TrendMonitor] Listing failed for ${designId}:`, err.message);
    });
    sendJson(res, { ok: true, message: 'Listing to Shopify started' });
    return true;
  }

  // DELETE /api/trends/:id — dismiss/archive a trend
  const deleteMatch = pathname.match(/^\/api\/trends\/([^/]+)$/);
  if (deleteMatch && req.method === 'DELETE') {
    const archived = archiveTrend(deleteMatch[1]);
    sendJson(res, { ok: archived, message: archived ? 'Trend archived' : 'Trend not found' });
    return true;
  }

  return false;
}

// =============================================================================
// EXPORTS
// =============================================================================

module.exports = {
  handleTrendMonitorRoute,
  runTrendScan,
  fetchRedditTrends,
  fetchGoogleTrends,
  analyzeTrendsWithClaude,
  generateDesignForTrend,
  listDesignToShopify,
  sendTrendAlerts,
  approveDesign,
  rejectDesign,
  listApprovedDesign,
  archiveTrend,
  loadData,
  saveData,
  DEFAULT_SETTINGS
};
