#!/usr/bin/env node
/**
 * Manifold Boolean Worker
 * Runs in a child process to avoid WASM issues in Electron main process.
 *
 * Usage: node manifold-worker.js <baseStl> <cutterStl> <outputStl>
 */
const fs = require('fs');

const [,, baseStlPath, cutterStlPath, outputPath] = process.argv;

if (!baseStlPath || !cutterStlPath || !outputPath) {
  console.error('Usage: node manifold-worker.js <baseStl> <cutterStl> <outputStl>');
  process.exit(1);
}

function parseStlToMesh(stlPath) {
  const buf = fs.readFileSync(stlPath);
  const header = buf.slice(0, 5).toString('ascii');
  if (header === 'solid') return parseAsciiStl(buf);
  return parseBinaryStl(buf);
}

function parseAsciiStl(buf) {
  const text = buf.toString('ascii');
  const vertMap = new Map();
  const verts = [];
  const triIndices = [];

  function getIdx(x, y, z) {
    const key = x.toFixed(5) + ',' + y.toFixed(5) + ',' + z.toFixed(5);
    if (vertMap.has(key)) return vertMap.get(key);
    const idx = verts.length / 3;
    verts.push(x, y, z);
    vertMap.set(key, idx);
    return idx;
  }

  const vertexRegex = /vertex\s+([-\d.eE+]+)\s+([-\d.eE+]+)\s+([-\d.eE+]+)/g;
  let match;
  const faceVerts = [];
  while ((match = vertexRegex.exec(text)) !== null) {
    faceVerts.push(getIdx(parseFloat(match[1]), parseFloat(match[2]), parseFloat(match[3])));
    if (faceVerts.length === 3) {
      triIndices.push(faceVerts[0], faceVerts[1], faceVerts[2]);
      faceVerts.length = 0;
    }
  }

  return { vertProperties: new Float32Array(verts), triVerts: new Uint32Array(triIndices), numProp: 3 };
}

function parseBinaryStl(buf) {
  const reportedTris = buf.readUInt32LE(80);
  const maxTris = Math.floor((buf.length - 84) / 50);
  const triCount = Math.min(reportedTris, maxTris);

  const vertMap = new Map();
  const verts = [];
  const triIndices = [];

  function getIdx(x, y, z) {
    const key = x.toFixed(5) + ',' + y.toFixed(5) + ',' + z.toFixed(5);
    if (vertMap.has(key)) return vertMap.get(key);
    const idx = verts.length / 3;
    verts.push(x, y, z);
    vertMap.set(key, idx);
    return idx;
  }

  for (let i = 0; i < triCount; i++) {
    const off = 84 + i * 50;
    for (let v = 0; v < 3; v++) {
      triIndices.push(getIdx(
        buf.readFloatLE(off + 12 + v * 12),
        buf.readFloatLE(off + 12 + v * 12 + 4),
        buf.readFloatLE(off + 12 + v * 12 + 8)
      ));
    }
  }

  return { vertProperties: new Float32Array(verts), triVerts: new Uint32Array(triIndices), numProp: 3 };
}

function writeMeshToStl(mesh, outputPath) {
  const vp = mesh.vertProperties;
  const tv = mesh.triVerts;
  const np = mesh.numProp;
  const triCount = tv.length / 3;

  const buf = Buffer.alloc(84 + triCount * 50);
  buf.write('BRCC Dog Tag - Generated by manifold-3d', 0, 80, 'ascii');
  buf.writeUInt32LE(triCount, 80);

  for (let i = 0; i < triCount; i++) {
    const off = 84 + i * 50;
    const i0 = tv[i * 3], i1 = tv[i * 3 + 1], i2 = tv[i * 3 + 2];
    const v0 = [vp[i0 * np], vp[i0 * np + 1], vp[i0 * np + 2]];
    const v1 = [vp[i1 * np], vp[i1 * np + 1], vp[i1 * np + 2]];
    const v2 = [vp[i2 * np], vp[i2 * np + 1], vp[i2 * np + 2]];

    const e1 = [v1[0] - v0[0], v1[1] - v0[1], v1[2] - v0[2]];
    const e2 = [v2[0] - v0[0], v2[1] - v0[1], v2[2] - v0[2]];
    const nx = e1[1] * e2[2] - e1[2] * e2[1];
    const ny = e1[2] * e2[0] - e1[0] * e2[2];
    const nz = e1[0] * e2[1] - e1[1] * e2[0];
    const len = Math.sqrt(nx * nx + ny * ny + nz * nz) || 1;

    buf.writeFloatLE(nx / len, off);
    buf.writeFloatLE(ny / len, off + 4);
    buf.writeFloatLE(nz / len, off + 8);

    for (let j = 0; j < 3; j++) {
      const vi = tv[i * 3 + j];
      buf.writeFloatLE(vp[vi * np],     off + 12 + j * 12);
      buf.writeFloatLE(vp[vi * np + 1], off + 12 + j * 12 + 4);
      buf.writeFloatLE(vp[vi * np + 2], off + 12 + j * 12 + 8);
    }
    buf.writeUInt16LE(0, off + 48);
  }

  fs.writeFileSync(outputPath, buf);
  return triCount;
}

(async () => {
  try {
    const Module = require('manifold-3d/manifold.js');
    const wasm = await Module.default();
    const { Manifold } = wasm;

    const baseMesh = parseStlToMesh(baseStlPath);
    const cutterMesh = parseStlToMesh(cutterStlPath);

    const base = new Manifold(baseMesh);
    const cutter = new Manifold(cutterMesh);

    const result = base.subtract(cutter);
    const outMesh = result._GetMeshJS();
    const triCount = writeMeshToStl(outMesh, outputPath);

    // Output JSON result for parent process to parse
    console.log(JSON.stringify({
      success: true,
      triCount,
      volume: result.volume(),
      baseVol: base.volume(),
      cutterVol: cutter.volume(),
    }));
  } catch (err) {
    console.error(JSON.stringify({ success: false, error: err.message }));
    process.exit(1);
  }
})();
